# -----------Font-----------------
font_family        MesloLGS NF
bold_font	   MesloLGS NF Bold
italic_font	   MelsoLGS NF Italic
font_size           13.0

#------------Window--------
window_padding_width   12
background_opacity     0.90
dynamic_background_opacity  yes


cursor_shape           beam
cursor_blink_interval  0.5
adjust_line_height     120%
adjust_column_width    105%

tab_bar_style          powerline
tab_powerline_style    slanted

enable_audio_bell      no
