# Default: cinematic movies
[default]
hwdec=auto-safe
vo=gpu-next
gpu-api=opengl

scale=ewa_lanczossharp
cscale=ewa_lanczossharp

interpolation=no
video-sync=audio


# Anime profile
[anime]
hwdec=auto-safe
vo=gpu-next
gpu-api=vulkan

scale=ewa_lanczos
cscale=ewa_lanczos

interpolation=no
video-sync=audio

# Optional anime enhancements
deband=yes
deband-iterations=2
deband-threshold=35
glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"
